### ISSUE TITLE
Migração de componentes que não definem estratégias de metapesquisas

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/bvs-site-importer#1]
Após os procedimentos de conversão do XML do BVS-Site para WP, ao realizarmos a importação do mesmo, os componentes que não definem estratégias de metapesquisas não são migrados.

**Comment by moacirmoda** [comment]
Componentes que não estão sendo migrados:
- 18
- 19

**Comment by moacirmoda** [comment]
Agora todos os tipos de registros são migrados.
