### ISSUE TITLE
Migração de conteúdo do campo Página do Portal (XHTML) como página no WP

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/bvs-site-importer#2]
Nos componentes que possuem conteúdo no campo Página do Portal (XHTML) deveria haver uma condição no script para gerar uma página no WP que replicasse esse conteúdo, pois atualmente essa informação está sendo desprezada na migração.

**Comment by moacirmoda** [comment]
**Encaminhamento imediato:**
- Concatenar os campos **description** e **portal** e exibir no body do vhl_collection
  - (o usuário decide o que vai fazer com a informação: criar outra página, deletar informação, adaptar informação, etc)

**Encaminhamento futuro:**
- Estudar implementação de excerpt no vhl_collection (plugin Page Excerpt)
